-- MySQL Script generated by MySQL Workbench
-- Sat Apr 19 14:12:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cv_xpto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cv_xpto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cv_xpto` DEFAULT CHARACTER SET utf8 ;
USE `cv_xpto` ;

-- -----------------------------------------------------
-- Table `cv_xpto`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cv_xpto`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(60) NOT NULL,
  `departamento` VARCHAR(70) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(75) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `roleacesso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cv_xpto`.`CartaoDeVisita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cv_xpto`.`CartaoDeVisita` (
  `idCartaoDeVisita` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(60) NOT NULL,
  `departamento` VARCHAR(60) NOT NULL,
  `telefoneCorporativo` INT NOT NULL,
  `emailProfiisional` VARCHAR(100) NOT NULL,
  `enderecoDaEmpresa` VARCHAR(55) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idCartaoDeVisita`, `usuario_idusuario`),
  INDEX `fk_CartaoDeVisita_usuario_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_CartaoDeVisita_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `cv_xpto`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cv_xpto`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cv_xpto`.`historico` (
  `idhistorico` INT NOT NULL AUTO_INCREMENT,
  `listaDeCartoesGerados` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idhistorico`, `usuario_idusuario`),
  INDEX `fk_historico_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_historico_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `cv_xpto`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cv_xpto`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cv_xpto`.`relatorio` (
  `idrelatorio` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idrelatorio`, `usuario_idusuario`),
  INDEX `fk_relatorio_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_relatorio_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `cv_xpto`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
