-- MySQL Script generated by MySQL Workbench
-- Tue Mar  4 22:23:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cv_xpto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cv_xpto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cv_xpto` DEFAULT CHARACTER SET utf8 ;
USE `cv_xpto` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cv_xpto`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(60) NOT NULL,
  `departamento` VARCHAR(70) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(75) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cv_xpto`.`administrador` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `email` VARCHAR(70) NULL,
  `senha` VARCHAR(255) NULL,
  `gestaoDeAcesso` VARCHAR(100) NULL,
  PRIMARY KEY (`idadministrador`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cv_xpto`.`relatorio` (
  `idrelatorio` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NULL,
  `administrador_idadministrador` INT NOT NULL,
  PRIMARY KEY (`idrelatorio`, `administrador_idadministrador`),
  INDEX `fk_relatorio_administrador1_idx` (`administrador_idadministrador` ASC) ,
  CONSTRAINT `fk_relatorio_administrador1`
    FOREIGN KEY (`administrador_idadministrador`)
    REFERENCES `cv_xpto`.`administrador` (`idadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cv_xpto`.`historico` (
  `idhistorico` INT NOT NULL AUTO_INCREMENT,
  `listaDeCartoesGerados` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idhistorico`, `usuario_idusuario`),
  INDEX `fk_historico_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_historico_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `cv_xpto`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`CartaoDeVisita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cv_xpto`.`CartaoDeVisita` (
  `idCartaoDeVisita` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(60) NOT NULL,
  `departamento` VARCHAR(60) NOT NULL,
  `telefoneCorporativo` INT NOT NULL,
  `emailProfissional` VARCHAR(100) NOT NULL,
  `enderecoDaEmpresa` VARCHAR(55) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `administrador_idadministrador` INT NOT NULL,
  PRIMARY KEY (`idCartaoDeVisita`, `usuario_idusuario`, `administrador_idadministrador`),
  INDEX `fk_CartaoDeVisita_usuario_idx` (`usuario_idusuario` ASC),
  INDEX `fk_CartaoDeVisita_administrador1_idx` (`administrador_idadministrador` ASC),
  CONSTRAINT `fk_CartaoDeVisita_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `cv_xpto`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CartaoDeVisita_administrador1`
    FOREIGN KEY (`administrador_idadministrador`)
    REFERENCES `cv_xpto`.`administrador` (`idadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
